### ISSUE TITLE
Facets Padding / Sizing...

### ISSUE THREAD

**Issue by dbouwman** [Esri/ember-arcgis-portal-components#63]
This is on PROD

This can be seen when linking an existing item into an initiative (any)
![image](https://user-images.githubusercontent.com/119129/37985977-83fe8660-31b7-11e8-9fc3-e6478a99a42a.png)

This is choosing a dataset for a chart card
![image](https://user-images.githubusercontent.com/119129/37986462-beff561c-31b8-11e8-91ad-9bf4fe55d77c.png)

**Comment by briandaviddavidson** [comment]
@dbouwman 

This is related to a [previous ticket](https://esriarlington.tpondemand.com/entity/83367-boundary-of-item-picker-content) ([designs for that ticket here](https://esri.invisionapp.com/share/MUFMZDZ54SK#/screens/274607876)) I had about adding more spacing to the item picker. I can take the extra padding out and put it back to what it originally was. I'll confirm with @BRolly8908 and @samanthahunter

**Comment by BRolly8908** [comment]
@briandaviddavidson the extra padding was requested for the full-screen modal as many of the UI elements of the modal were difficult to see at the edges of the window with very little padding between UI and screen-edge.  This is obviously not the case for a modal that is not full-screen as the background area cues visual focus.

**Comment by briandaviddavidson** [comment]
@BRolly8908 Correct. This was what solved that, but it obviously broke it in other places. I'll readd the padding for the full screen modal, but that will more than likely be in the actual opendata-admin as opposed to in the item picker

**Comment by briandaviddavidson** [comment]
#69 has been merged. Closing
